### ISSUE TITLE
Build the front page

### ISSUE THREAD

**Issue by matoval** [CCWebDevJobBoard/JobBoard#19]
Build the front page following the instructions on the readMe, the Style Guide and using the mockup that is attached here.

![CCJobBoard (1)](https://user-images.githubusercontent.com/53712446/70349561-c8c7ae80-1819-11ea-9cff-53e9105cb55f.png)

**Comment by shivenigma** [comment]
Can you assign me to it? I am not exactly sure how to assign just wanted to make sure that two people won't end up doing the same thing.

**Comment by matoval** [comment]
Sorry I didn't close this issue, this page was built yesterday. But I am adding two new issues for pages to be built.

**Comment by shivenigma** [comment]
Okay, Thanks. I was just about to start.
