### ISSUE TITLE
Creating a mockup

### ISSUE THREAD

**Issue by kzollove** [CCWebDevJobBoard/JobBoard#27]
@matoval 
@pablowbk 

How do you go about creating a mockup? (This is my first collab web project, sorry for newbie Q)

**Comment by pablowbk** [comment]
Hi @kzollove ! some are using Figma, but whichever tool you're confortable with is fine. No need to be sorry, we are all learning here. Mattew ignited a spark and it is up to everybody to keep that spark alive =) 
Check out the readme, as well as the existing issues before moviing on. And there's the Slack channel for discussions and chit chat
