### ISSUE TITLE
build a search page

### ISSUE THREAD

**Issue by matoval** [CCWebDevJobBoard/JobBoard#3]
build a search page with a search input on top under the header and a results field under the search input.

**Comment by pablowbk** [comment]
should this be a separate page, or maybe we can get the search working in the home page, maybe adding typeahead functionality. Don't know if I can pull it off , but would love try

**Comment by matoval** [comment]
Either way will work. A separate page or a section on the homepage. It would be nice to have it search on every character that is inputed. If you would like to build this and need some help let me know. I can help you if you get stuck.

**Comment by matoval** [comment]
I'm adding a mock up issue for this issue.
